# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 117169661e298a265cb968f397b751ae2d19572e27bbaaccab6b153d2be592f7fed2a324504af361d8df987ff611f6e1d3047e6ca6a9602c42d1ab345dd30fac

test:
  secret_key_base: ec19e27f83e3a1c4f8f6cf06e57c3f41b35ebc8b62352c33c243bb7a985ca8ada506b39cc2640b996744e28d4c3b72dd36a4d707d9a6a8b4e6612843dcb2b703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
