

development:
  adapter: postgresql
  database: spree/core_spree_development
  username: postgres
  min_messages: warning

test:
  adapter: postgresql
  database: spree/core_spree_test
  username: postgres
  min_messages: warning

production:
  adapter: postgresql
  database: spree/core_spree_production
  username: postgres
  min_messages: warning


