# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b6a817e6398d06f7581c1220e732a66a6fc1cdc0548003e3e2d7a11b0eb504afff32241999c5551d5d350802840c0e24c38f2958b864696a438e6ce80ee8e00

test:
  secret_key_base: 6b66ed884697e7bd6df58f113d345e096253db3f7d132d448350840c7a855fe7e296b44088a2ed3b9abcea0504139231a27b512c8aa804e0a9e67fd3b5e01e85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
